### PR TITLE
Move code to a subdirectory

### PR DESCRIPTION
**Pull request by natebosch**
We need to make room for a second package in this repository. This also helps current organization since it doesn't make sense for `workspace` to be a subdirectory of the package.

- Move most code to a directory named `dazel`. This will be the long term name for the package so avoid a second big shuffle when we get around to that.
- Keep `workspace` and `tool` at the top level since they are for testing with travis
- Add a top level pubspec.yaml with only what is needed for the presubmit.dart tool
- Update .gitignore to reflect that some of the generated files and directories won't exist at the top level
- Move the `bazelify` specific documentation into the README for that package

### CODE REVIEW

**Comment by kevmoo** [comment]
@natebosch travis are sad: https://travis-ci.org/dart-lang/bazel/builds/196055187#L441

**Comment by natebosch** [comment]
Yeah I'm hoping the latest commit fixes travis. Unfortunately I can try to do what travis does manually to confirm - but I can't actually recreate the whole travis environment so I have to guess and check a bit.

**Comment by nshahan** [comment]
When are we going to settle the name? It is starting to look confusing with the package name "bazel" the directory "dazel" and the command "bazelify".

**Comment by kevmoo** [comment]
We can start renaming things as soon as you want – although let me google dazel first 😄

**Comment by natebosch** [comment]
All 3 - package, directory, command - should be dazel once we have the rename. Top level repo will likely still be bazel. The next directory I create will be bazel_codegen

**Pull request merged**
